version: 2
jobs:
  test:
    docker:
      - image: circleci/node:12.16
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: yarn
      - run:
          name: Lint
          command: yarn lint
      - run:
          name: Test Coverage
          command: yarn test
  deploy:
    docker:
      - image: circleci/node:12.16
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: yarn
      - run:
          name: build_deploy
          command: npm publish --access public
workflows:
  version: 2
  test-wf:
    jobs:
      - test

  deploy-wf:
    jobs:
      - test:
          filters:
            branches:
              only:
                - develop

      - deploy:
          requires:
            - test
          filters:
            branches:
              only:
                - develop    
